name: Cypress Automation Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Cypress

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --browser electron

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: Cypress/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: Cypress/cypress/videos
          if-no-files-found: ignore

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: Cypress/cypress/reports
          if-no-files-found: ignore